dyniva_core.managed_entity.*:
  type: config_entity
  label: 'Managed entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Entity bundle'
    display_mode:
      type: string
      label: 'Manage view display mode'
    form_mode:
      type: string
      label: 'Manage form display mode'
    module_name:
      type: string
      label: 'Defined module name'
    has_draft:
      type: boolean
      label: 'Has draft'
    standalone:
      type: boolean
      label: 'Is standalone'
    uuid:
      type: string
    plugins:
      type: sequence
      label: 'plugins status'
